stages:
  - test

phpunit:
  stage: test
  image: php:8.3-cli
  only:
    - test
  before_script:
    - apt-get update && apt-get install -y unzip libsqlite3-dev
    - docker-php-ext-install pdo_sqlite
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --working-dir=src
  script:
    - src/vendor/bin/phpunit --configuration phpunit.xml
