name: Tests

on:
  push:
    branches: [test]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_sqlite

      - name: Install dependencies
        run: composer install --working-dir=src

      - name: Run PHPUnit
        run: src/vendor/bin/phpunit --configuration phpunit.xml
